<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130816173914 extends AbstractMigration
{
    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ttree_identicons_domain_model_identicon DROP FOREIGN KEY FK_6D8EFFACBC91F416");
        $this->addSql("DROP INDEX UNIQ_6D8EFFACBC91F416 ON ttree_identicons_domain_model_identicon");
        $this->addSql("ALTER TABLE ttree_identicons_domain_model_identicon CHANGE resource image VARCHAR(40) DEFAULT NULL");
        $this->addSql("ALTER TABLE ttree_identicons_domain_model_identicon ADD CONSTRAINT FK_6D8EFFACC53D045F FOREIGN KEY (image) REFERENCES typo3_media_domain_model_image (persistence_object_identifier)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_6D8EFFACC53D045F ON ttree_identicons_domain_model_identicon (image)");
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ttree_identicons_domain_model_identicon DROP FOREIGN KEY FK_6D8EFFACC53D045F");
        $this->addSql("DROP INDEX UNIQ_6D8EFFACC53D045F ON ttree_identicons_domain_model_identicon");
        $this->addSql("ALTER TABLE ttree_identicons_domain_model_identicon CHANGE image resource VARCHAR(40) DEFAULT NULL");
        $this->addSql("ALTER TABLE ttree_identicons_domain_model_identicon ADD CONSTRAINT FK_6D8EFFACBC91F416 FOREIGN KEY (resource) REFERENCES typo3_media_domain_model_image (persistence_object_identifier)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_6D8EFFACBC91F416 ON ttree_identicons_domain_model_identicon (resource)");
    }
}
