<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130816161351 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE ttree_identicons_domain_model_identicon (token VARCHAR(255) NOT NULL, resource VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_6D8EFFACBC91F416 (resource), PRIMARY KEY(token))");
		$this->addSql("ALTER TABLE ttree_identicons_domain_model_identicon ADD CONSTRAINT FK_6D8EFFACBC91F416 FOREIGN KEY (resource) REFERENCES typo3_media_domain_model_image (persistence_object_identifier)");
		$this->addSql("DROP TABLE ttree_notificationcenter_domain_model_notification");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE ttree_notificationcenter_domain_model_notification (persistence_object_identifier VARCHAR(40) NOT NULL, account VARCHAR(40) DEFAULT NULL, creationdate DATETIME NOT NULL, status INT NOT NULL, type VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, data LONGTEXT NOT NULL COMMENT '(DC2Type:array)', body LONGTEXT NOT NULL, INDEX IDX_26BCA4477D3656A4 (account), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE ttree_notificationcenter_domain_model_notification ADD CONSTRAINT FK_26BCA4477D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE ttree_identicons_domain_model_identicon");
	}
}

?>